### PR TITLE
The number of params to unpack maybe wrong

### PR DESCRIPTION
**Pull request by chenzhutian**
Possible unbalanced tuple unpacking with sequence defined at line 406 of etw_pytorch_utils.pytorch_utils: left side has 2 label(s), right side has 3 value(s)
According to the source code:

https://github.com/erikwijmans/etw_pytorch_utils/blob/v1.0.0/etw_pytorch_utils/pytorch_utils.py#L380-L396

Besides, is it the `best_prec` the same as `best_loss`?

### CODE REVIEW

**Comment by chenzhutian** [comment]
This problem also exists in https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2/train/train_cls.py#L109-L110

**Comment by erikwijmans** [comment]
Yep, this is a bug (looks like I didn't update the checkpoint reloading when I changed the trainer to support iterations).

Couple other things needs to change:  `last_epoch=start_epoch` needs to be changed to `last_epoch=it` in the LR and BNM schedulers: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2/train/train_cls.py#L114

`trainer.train` needs to be called with `it` instead of `0` for the first argument: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/pointnet2/train/train_cls.py#L147

And `it = 0` needs to be added for the case where a checkpoint isn't reloaded.

`best_prec` is the same as `best_loss` as the trainer is passing `best_loss` in as `best_prec`.

**Comment by chenzhutian** [comment]
Revised as advised.
It should be updated together with https://github.com/erikwijmans/etw_pytorch_utils/pull/2

**Comment by erikwijmans** [comment]
Changes to `pointnet2/train/train_cls.py` look great!  Can you also make the same set of changes to `pointnet2/train/train_sem_seg.py`?  It uses the same training logic.

**Comment by chenzhutian** [comment]
No problem. Done.

**Comment by erikwijmans** [comment]
Thank you very much!  Merging.

**Pull request merged**
